server:
  port: 9094

elasticsearch:
  hostlist: 192.168.88.128:9200 #多个结点中间用逗号分隔
  course:
    index: course-publish
    source_fields: id,name,grade,mt,st,charge,pic,price,originalPrice,teachmode,validDays,createDate